TEST_API_KEY = "organizations/test-organization/apiKeys/test-api-key"
TEST_API_SECRET = "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIKwf3Uox30cRWzRBOPoPOH5p0Gpb0Dt8zUKXUEM5fMkGoAoGCCqGSM49\nAwEHoUQDQgAEbAtpLlSZYVOwYICz+uEyxcS29vRIujiES/gQ1DC7FV4zK4JuYE9v\nqDyGZQYjdXHLM7I6f/QnnOITL+dXYWBHRA==\n-----END EC PRIVATE KEY-----\n"
TEST_ED25519_API_SECRET = "k0BUni0p0vZG1BdpVjS6ogBJ7kxm630AJ2dN+tuputDOKsRAwgyrpEQLeBtS1znTmzPX6Xr2eOWpzx6nW8knkA=="
# Same key as TEST_ED25519_API_SECRET, wrapped in PKCS8 PEM (-----BEGIN PRIVATE KEY-----)
TEST_ED25519_PKCS8_API_SECRET = "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIJNAVJ4tKdL2RtQXaVY0uqIASe5MZut9ACdnTfrbqbrQ\n-----END PRIVATE KEY-----\n"
# Same key as TEST_ED25519_API_SECRET, raw 32-byte seed only (base64)
TEST_ED25519_SEED_API_SECRET = "k0BUni0p0vZG1BdpVjS6ogBJ7kxm630AJ2dN+tuputA="
